version: '3.9'
services:
  s3:
    image: minio/minio
    container_name: wiki-minio-rem
    environment:
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_wiki_storage:/data
    command: server --console-address ":9001" /data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  postgresql:
    image: postgres
    container_name: wiki-postgres-rem
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: wiki_server
    ports:
      - "5432:5432"
    volumes:
      - postgresql_wiki:/var/lib/mysql
  spring-app:
    image: ulyanabelyaeva/wiki-server:1
    container_name: spring-app
    ports:
      - "8091:8091"
    depends_on:
     - postgresql
     - s3
  react-app:
    image: ulyanabelyaeva/wiki-web-client:1
    container_name: react-app
    ports:
      - "3000:3000"
    depends_on:
     - spring-app

volumes:
  minio_wiki_storage: {}
  postgresql_wiki: {}
